# Generated by Django 6.0.5 on 2026-06-06 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('motif', models.TextField()),
                ('statut', models.CharField(default='En attente', max_length=50)),
                ('dentiste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabinet.dentiste')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabinet.patient')),
            ],
        ),
        migrations.DeleteModel(
            name='rendez_vous',
        ),
    ]
