# Generated by Django 6.0.6 on 2026-07-11 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0002_rendezvous_delete_rendez_vous'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date_paiement', models.DateField(auto_now_add=True)),
                ('mode_paiement', models.CharField(choices=[('especes', 'Espèces'), ('carte', 'Carte bancaire'), ('virement', 'Virement')], default='especes', max_length=50)),
                ('rendezvous', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cabinet.rendezvous')),
            ],
        ),
    ]
